### ISSUE TITLE
v1.3.0 does not work in Java 17

### ISSUE THREAD

**Issue by RolKau** [jsslkeylog/jsslkeylog#4]
Example:

    $ /usr/lib/jvm/java-11-openjdk-amd64/bin/java -version
    openjdk version "11.0.11" 2021-04-20
    OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
    OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

    $ /usr/lib/jvm/java-17-openjdk-amd64/bin/java -version
    openjdk version "17.0.1" 2021-10-19
    OpenJDK Runtime Environment (build 17.0.1+12-Ubuntu-120.04)
    OpenJDK 64-Bit Server VM (build 17.0.1+12-Ubuntu-120.04, mixed mode, sharing)

    $ cat > Repro.java <<EOF
    import java.net.URL;
    import java.io.InputStreamReader;
    import java.io.BufferedReader;
    import javax.net.ssl.HttpsURLConnection;
    public class Repro {
      public static void main(String[] args) throws Exception {
        HttpsURLConnection conn = (HttpsURLConnection) new URL(args[0]).openConnection();
        try (BufferedReader br = new BufferedReader(new InputStreamReader(conn.getInputStream()))) {
          for (;;) {
            String line = br.readLine();
              if (line == null) {
                break;
              }
              System.out.println(line);
          }
        }
      }
    }
    EOF

    $ /usr/lib/jvm/java-11-openjdk-amd64/bin/javac Repro.java

    $ /usr/lib/jvm/java-11-openjdk-amd64/bin/java -javaagent:jSSLKeyLog-1.3.jar=ssl-java11.log -cp . Repro https://github.com >/dev/null

    $ fgrep -c ssl-java11.log
    4

    $ /usr/lib/jvm/java-17-openjdk-amd64/bin/java -javaagent:jSSLKeyLog-1.3.jar=ssl-java17.log -cp . Repro https://github.com >/dev/null

    $ fgrep -c ssl-java17.log
    0

**Comment by schierlm** [comment]
Not surprising, as the README mentions it was only tested up to Java 15.

It may be as easy as updating the ASM dependency to latest version; but it may also require adding more instrumentation classes and/or instrumentation rules.

Thanks for the reminder, though, I will try to update it when I can find time to do so. Pull requests are greatly appreciated, though.

**Comment by RolKau** [comment]
> it was only tested up to Java 15

Yes, I know; Java 17 was released after jSSLKeyLog 1.3, and I didn't expect it to be forward compatible. :-)

> updating the ASM dependency to latest version

Thanks for the tip! I tried to update to org.ow2.asm:asm:9.2 but unfortunately it seems to be necessary but not sufficient.

I guess the real problem is the removal of the context field in line 71 in SSLSecretDerivation.java in this commit:
https://github.com/openjdk/jdk/commit/dcf63f857872489a082be970438b5365c7a83b4a#diff-82a1cca2f87c6128fff95bf14b19922b91b18e1228d3ff519366b1fc5bfa3f69L71

Maybe the constructor must be instrumented as well to pick it up?

**Comment by schierlm** [comment]
Yeah, probably the easiest way would be to inject a new field (e.g. `$context`) and instrument the start of the constructor to assign it, effectively reverting the linked change).

**Comment by schierlm** [comment]
Sorry, took me a while to find time for this project again, and also took me some time to find out why I could not reproduce the problems you were facing with ASM 9.2 (it only happens for TLS 1.3 connections).

Can you please test if current master fixes the problem for you as well?

**Comment by RolKau** [comment]
Yes, I can confirm that master branch, commit e3c4f2b, indeed solves the problem! :-)

**Comment by schierlm** [comment]
I just pushed f5595cdb149214ed7fe5c99141eda6660dd32461 to support the new bytecode format of Java 21. Building is not possible with Java 21 as Java 21 does not support -target 1.7 any longer (only 1.8 or higher). So my two options are either drop -target 1.7 (and point to 1.3 for those old JDKs) or require an older JDK (tested down to 1.8) to build it.

@RolKau  What would you prefer for the upcoming release? Also, as you are using more bleeding edge Java versions than me, could you test whether the updated jsslkeylog works fine for you on Java 21? I just did a very short test, and logfiles look sane.

**Comment by RolKau** [comment]
@schierlm Sorry for the very late reply. Ideally, binary releases should be made with the release that gives the largest use span (which would be 17 then), while sources still being available to build with the newest version, I guess, for those that want to compile it themselves.

Unfortunately, I haven't been able to test it for Java 21; I've been waiting for the release to reach the Debian/Ubuntu repositories. I will report back once I have the opportunity.
